name: devoida
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: 1.8.1
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  get_it: ^7.6.7
  gap: ^3.0.1
  carousel_slider: ^4.2.1
  simple_gradient_text: ^1.3.0
  email_validator: ^3.0.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_database: ^11.0.2
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  intl: ^0.19.0
  uuid: ^4.4.0
  omni_datetime_picker: ^2.0.2
  fl_chart: ^0.68.0
  gantt_chart: ^0.3.0
  mailer: ^6.1.0
  dio: ^5.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/devoidalogo.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins-bold.ttf
          weight: 700
        - asset: assets/fonts/poppins-semi-bold.ttf
          weight: 600
        - asset: assets/fonts/poppins-medium.ttf
          weight: 500
        - asset: assets/fonts/poppins-regular.ttf
          weight: 400
        - asset: assets/fonts/poppins-light.ttf
          weight: 300
