// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnBAENWi4TTfHLnMESA9ha_UH29-k6ozw',
    appId: '1:369425102338:web:6359d507c9e13b744ad91b',
    messagingSenderId: '369425102338',
    projectId: 'devoida-2663d',
    authDomain: 'devoida-2663d.firebaseapp.com',
    storageBucket: 'devoida-2663d.appspot.com',
    measurementId: 'G-XYZ6FDVEJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgpY0Qw3aUbdt-L2_fa4HYT1E9dBxnX30',
    appId: '1:369425102338:android:8b2b8c663d2ff1994ad91b',
    messagingSenderId: '369425102338',
    projectId: 'devoida-2663d',
    storageBucket: 'devoida-2663d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5C6ythADNznzUrS2ZA-uBhzh_7lrOM0',
    appId: '1:369425102338:ios:ba4a7b90ad3fea5e4ad91b',
    messagingSenderId: '369425102338',
    projectId: 'devoida-2663d',
    storageBucket: 'devoida-2663d.appspot.com',
    iosBundleId: 'com.example.devoida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5C6ythADNznzUrS2ZA-uBhzh_7lrOM0',
    appId: '1:369425102338:ios:ba4a7b90ad3fea5e4ad91b',
    messagingSenderId: '369425102338',
    projectId: 'devoida-2663d',
    storageBucket: 'devoida-2663d.appspot.com',
    iosBundleId: 'com.example.devoida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnBAENWi4TTfHLnMESA9ha_UH29-k6ozw',
    appId: '1:369425102338:web:0b19c0b2aeb384ac4ad91b',
    messagingSenderId: '369425102338',
    projectId: 'devoida-2663d',
    authDomain: 'devoida-2663d.firebaseapp.com',
    storageBucket: 'devoida-2663d.appspot.com',
    measurementId: 'G-G3XQDBS7VL',
  );
}
